-- MySQL Script generated by MySQL Workbench
-- mer. 11 nov. 2020 20:41:10 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BreizhVideo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BreizhVideo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BreizhVideo` ;
USE `BreizhVideo` ;

-- -----------------------------------------------------
-- Table `BreizhVideo`.`actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BreizhVideo`.`actor` (
  `actor_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`actor_id`),
  INDEX `idx_actor_last_name` (`last_name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 201
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BreizhVideo`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BreizhVideo`.`category` (
  `category_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BreizhVideo`.`film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BreizhVideo`.`film` (
  `film_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `release_year` YEAR NULL DEFAULT NULL,
  `length` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `special_features` SET('Trailers', 'Commentaries', 'Deleted Scenes', 'Behind the Scenes') NULL DEFAULT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`film_id`),
  INDEX `idx_title` (`title` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1001
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BreizhVideo`.`film_actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BreizhVideo`.`film_actor` (
  `actor_id` SMALLINT UNSIGNED NOT NULL,
  `film_id` SMALLINT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`actor_id`, `film_id`),
  INDEX `idx_fk_film_id` (`film_id` ASC) VISIBLE,
  CONSTRAINT `fk_film_actor_actor`
    FOREIGN KEY (`actor_id`)
    REFERENCES `BreizhVideo`.`actor` (`actor_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_film_actor_film`
    FOREIGN KEY (`film_id`)
    REFERENCES `BreizhVideo`.`film` (`film_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BreizhVideo`.`film_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BreizhVideo`.`film_category` (
  `film_id` SMALLINT UNSIGNED NOT NULL,
  `category_id` TINYINT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`film_id`, `category_id`),
  INDEX `fk_film_category_category` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_film_category_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `BreizhVideo`.`category` (`category_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_film_category_film`
    FOREIGN KEY (`film_id`)
    REFERENCES `BreizhVideo`.`film` (`film_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `BreizhVideo`.`village`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BreizhVideo`.`village` (
  `idVillage` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `CP` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVillage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BreizhVideo`.`preference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BreizhVideo`.`preference` (
  `idPreference` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Vote` VARCHAR(45) NULL,
  `village_idVillage` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPreference`, `village_idVillage`),
  INDEX `fk_preference_village1_idx` (`village_idVillage` ASC) VISIBLE,
  CONSTRAINT `fk_preference_village1`
    FOREIGN KEY (`village_idVillage`)
    REFERENCES `BreizhVideo`.`village` (`idVillage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BreizhVideo`.`show`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BreizhVideo`.`show` (
  `idshow` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `village_idVillage` INT UNSIGNED NOT NULL,
  `film_film_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idshow`, `village_idVillage`, `film_film_id`),
  INDEX `fk_show_village1_idx` (`village_idVillage` ASC) VISIBLE,
  INDEX `fk_show_film1_idx` (`film_film_id` ASC) VISIBLE,
  CONSTRAINT `fk_show_village1`
    FOREIGN KEY (`village_idVillage`)
    REFERENCES `BreizhVideo`.`village` (`idVillage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_show_film1`
    FOREIGN KEY (`film_film_id`)
    REFERENCES `BreizhVideo`.`film` (`film_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
